### ISSUE TITLE
QUESTION - query

### ISSUE THREAD

**Issue by juanr2001** [ChenLi0830/dynamoLight#2]
Can you please create an example on how to use the query just like you showed using scan?
Thank you!

**Comment by ChenLi0830** [comment]
Hey @juanr2001, I added some examples for queries. I hope they are helpful! https://github.com/ChenLi0830/dynamoLight#query
https://github.com/ChenLi0830/dynamoLight#query-1

**Comment by ChenLi0830** [comment]
@juanr2001 I made some small changes to the package, please make sure to reinstall the package 
```
npm remove dynamo-light --save
npm install dynamo-light --save
```

**Comment by ChenLi0830** [comment]
Hi @juanr2001, does that solve your question? If not please let me know.

**Comment by ChenLi0830** [comment]
Closing the issue. @juanr2001 Feel free to reopen if the issue persist for you.
